In [192]:
import os

print("Current working directory:", os.getcwd())

Current working directory: c:\Users\Babak.Baradaranhezav\ml-projects\ml_airbnb_price_regression

In [193]:
from pathlib import Path
import os

# Set working directory only if not already set
cwd = Path.cwd()
if not (cwd / ".git").exists():
    for parent in cwd.parents:
        if (parent / ".git").exists():
            os.chdir(parent)
            print("Working directory set to repo root:", parent)
            break
    else:
        raise FileNotFoundError("Could not find .git repo root. Are you inside the correct project folder?")
else:
    print("Already in repo root:", cwd)

Already in repo root: c:\Users\Babak.Baradaranhezav\ml-projects\ml_airbnb_price_regression

In [194]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from math import radians, sin, cos, sqrt, atan2

# Load the dataset (adjust path as needed)
df = pd.read_csv("data/processed/cleaned_listings.csv")  # Update path if different

In [195]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,price_log
0,13188,https://www.airbnb.com/rooms/13188,2.025060e+13,6/25/2025,city scrape,Garden level studio in ideal loc.,Garden level studio suite with garden patio - ...,The uber hip Main street area is a short walk ...,https://a0.muscache.com/pictures/8408188/e1af6...,51466,...,4.90,4.81,Municipal registration number: 25-156058<br />...,f,1,1,0,0,1.93,4.919981
1,16611,https://www.airbnb.com/rooms/16611,2.025060e+13,6/21/2025,previous scrape,"1 block to skytrain station, shops,restaurant,...","My place is close to bank, coffee shops, groce...",Next block to Commercial Drive which has many ...,https://a0.muscache.com/pictures/82101/7127b63...,58512,...,5.00,3.67,NaN,f,5,5,0,0,0.03,NaN
2,18270,https://www.airbnb.com/rooms/18270,2.025060e+13,6/21/2025,city scrape,private rm in clean central 2BR apt,I have a bright furnished 2 bedroom suite on a...,"Lots of restaurants, coffee shops.<br />Easy a...",https://a0.muscache.com/pictures/108520241/aec...,70437,...,4.69,4.49,NaN,f,1,0,1,0,0.68,3.850148
3,18589,https://www.airbnb.com/rooms/18589,2.025060e+13,6/25/2025,city scrape,Commercial Drive B&B,"As hosts, we are welcoming you into our home, ...",Lots of restaurants and boutiques just outside...,https://a0.muscache.com/pictures/dd3ca406-cb74...,71508,...,4.93,4.96,Municipal registration number: 25-155972<br />...,f,1,0,1,0,3.54,5.236442
4,18795,https://www.airbnb.com/rooms/18795,2.025060e+13,6/21/2025,city scrape,*Best choice in downtown-5 Stars * -2,NaN,NaN,https://a0.muscache.com/pictures/96249/03d3af8...,70137,...,4.88,4.50,Municipal registration number: 18-573700,f,4,0,4,0,0.76,4.330733

In [196]:
# Define initial feature lists
numerical_features = [
    'accommodates', 'bathrooms', 'bedrooms', 'beds',
    'minimum_nights', 'maximum_nights',
    'number_of_reviews', 'review_scores_rating',
    'host_age_days', 'days_since_last_review', 'avg_review_score',
    'accommodates_bedrooms', 'min_nights_reviews', 'season', 'distance_to_center_km'
]

categorical_features = [
    'host_is_superhost', 'instant_bookable', 'room_type'
]  # Remove neighbourhood_cleansed for dummy handling

binary_amenities = []  # Will be populated with amenities and host flags

# Note: In feature_engineering, host_flags should reflect binary columns created
host_flags = {
    'host_has_profile_pic': 'host_has_profile_pic_binary',
    'host_identity_verified': 'host_identity_verified_binary'
}

In [197]:
# Feature engineering
# Drop rows with missing price
df = df.dropna(subset=["price"])

In [198]:
# Convert host_since to datetime with fixed reference
if 'host_since' in df.columns:
    df['host_since'] = pd.to_datetime(df['host_since'], errors='coerce')
    max_host_since = df['host_since'].max()
    df['host_age_days'] = (max_host_since - df['host_since']).dt.days.fillna(0)
    print("Added host_age_days using max host_since as reference.")
else:
    print("'host_since' not found in dataset.")

Added host_age_days using max host_since as reference.

In [199]:
# Convert last_review to datetime with fixed reference
if 'last_review' in df.columns:
    df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce')
    max_last_review = df['last_review'].max()
    df['days_since_last_review'] = (max_last_review - df['last_review']).dt.days.fillna(0)
    df['season'] = df['last_review'].dt.month % 12 // 3  # 0=Winter, 1=Spring, 2=Summer, 3=Fall
    print("Added 'days_since_last_review' and 'season' using max last_review as reference.")
else:
    print("'last_review' not found in dataset.")

Added 'days_since_last_review' and 'season' using max last_review as reference.

In [200]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,price_log,host_age_days,days_since_last_review,season
0,13188,https://www.airbnb.com/rooms/13188,2.025060e+13,6/25/2025,city scrape,Garden level studio in ideal loc.,Garden level studio suite with garden patio - ...,The uber hip Main street area is a short walk ...,https://a0.muscache.com/pictures/8408188/e1af6...,51466,...,f,1,1,0,0,1.93,4.919981,5696,0.0,2.0
2,18270,https://www.airbnb.com/rooms/18270,2.025060e+13,6/21/2025,city scrape,private rm in clean central 2BR apt,I have a bright furnished 2 bedroom suite on a...,"Lots of restaurants, coffee shops.<br />Easy a...",https://a0.muscache.com/pictures/108520241/aec...,70437,...,f,1,0,1,0,0.68,3.850148,5625,2002.0,0.0
3,18589,https://www.airbnb.com/rooms/18589,2.025060e+13,6/25/2025,city scrape,Commercial Drive B&B,"As hosts, we are welcoming you into our home, ...",Lots of restaurants and boutiques just outside...,https://a0.muscache.com/pictures/dd3ca406-cb74...,71508,...,f,1,0,1,0,3.54,5.236442,5621,0.0,2.0
4,18795,https://www.airbnb.com/rooms/18795,2.025060e+13,6/21/2025,city scrape,*Best choice in downtown-5 Stars * -2,NaN,NaN,https://a0.muscache.com/pictures/96249/03d3af8...,70137,...,f,4,0,4,0,0.76,4.330733,5626,754.0,2.0
5,20085,https://www.airbnb.com/rooms/20085,2.025060e+13,6/21/2025,city scrape,Cozy Oasis Uptown Garden Suite,"Your private, fully furnished suite is central...",This beautiful garden suite on a quiet tree-li...,https://a0.muscache.com/pictures/miso/Hosting-...,75986,...,f,1,1,0,0,0.43,4.510860,5608,297.0,2.0

In [201]:
if 'room_type' in df.columns:
    print("yes")
else:
    print("no")

yes

In [203]:
import pandas as pd

# One-hot encode room_type
print("Columns before room_type block:", df.columns.tolist())  # Debug print to check state
if 'room_type' in df.columns:
    print("Current columns before processing:", df.columns.tolist())  # Debug print
    
    # Check for existing room_type dummies and drop them
    room_dummies = [col for col in df.columns if col.startswith('room_')]
    if room_dummies:
        df.drop(columns=room_dummies, inplace=True)
        print(f"Dropped existing room_type dummies: {room_dummies}")
    
    # Encode and drop original column
    df['room_type'] = df['room_type'].fillna('Unknown')
    room_dummies = pd.get_dummies(df['room_type'], prefix='room', drop_first=True)
    df = pd.concat([df, room_dummies], axis=1)
    df.drop(columns=['room_type'], inplace=True)  # Drop original after encoding
    print("One-hot encoded 'room_type' and dropped original column")
    print("Columns after processing:", df.columns.tolist())  # Debug print
else:
    print("'room_type' not found in dataset. Skipping one-hot encoding. Check data loading or prior modifications.")

Columns before room_type block: ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'price_log', 'host_age_days', 'days_since_last_review', 'season']
'room_type' not found in dataset. Skipping one-hot encoding. Check data loading or prior modifications.

In [204]:
# Handle review scores
review_cols = [col for col in df.columns if col.startswith('review_scores_')]
print(f"Found review score columns: {review_cols}")

for col in review_cols:
    if df[col].dtype in ['float64', 'int64']:
        df[col] = df[col].fillna(df[col].median())  # Use median instead of mean
        print(f"Filled missing values in '{col}' with column median.")
    else:
        print(f"Skipping non-numeric column: {col}")

if review_cols:
    df['avg_review_score'] = df[review_cols].mean(axis=1).fillna(0)
    print("Added 'avg_review_score'")

Found review score columns: ['review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value']
Filled missing values in 'review_scores_rating' with column median.
Filled missing values in 'review_scores_accuracy' with column median.
Filled missing values in 'review_scores_cleanliness' with column median.
Filled missing values in 'review_scores_checkin' with column median.
Filled missing values in 'review_scores_communication' with column median.
Filled missing values in 'review_scores_location' with column median.
Filled missing values in 'review_scores_value' with column median.
Added 'avg_review_score'

In [205]:
# Convert host flags to binary
for col, new_col in host_flags.items():
    if col in df.columns:
        df[new_col] = df[col].map({'t': 1, 'f': 0}).fillna(0)
        binary_amenities.append(new_col)
        print(f"Converted {col} to binary as {new_col}")
    else:
        print(f"'{col}' not found in dataset.")

Converted host_has_profile_pic to binary as host_has_profile_pic_binary
Converted host_identity_verified to binary as host_identity_verified_binary

In [206]:
# Extract amenities and add interaction terms
if 'amenities' in df.columns:
    # Check for existing amenity columns and drop them
    amenity_cols = [col for col in df.columns if col.startswith('Has_')]
    if amenity_cols:
        df.drop(columns=amenity_cols, inplace=True)
        print(f"Dropped existing amenity columns: {amenity_cols}")
    
    df['amenities_cleaned'] = df['amenities'].str.replace(r"[{}\"]", "", regex=True)
    df['amenities_list'] = df['amenities_cleaned'].str.lower().str.split(",")
    df['accommodates_bedrooms'] = df['accommodates'] * df['bedrooms']
    df['min_nights_reviews'] = df['minimum_nights'] * df['number_of_reviews']

    def has_amenity(amenity):
        return df['amenities_list'].apply(lambda x: int(amenity in (x or [])) if isinstance(x, list) else 0)

    important_amenities = {
        'Has_Wifi': 'wifi',
        'Has_Kitchen': 'kitchen',
        'Has_Heating': 'heating',
        'Has_TV': 'tv',
        'Has_Essentials': 'essentials',
        'Has_Hair_Dryer': 'hair dryer',
        'Has_Iron': 'iron',
        'Has_Free_Parking': 'parking',
        'Has_Hangers': 'hangers',
        'Has_Laptop_Friendly_Workspace': 'laptop friendly workspace'
    }

    for col, keyword in important_amenities.items():
        df[col] = has_amenity(keyword)
        binary_amenities.append(col)
        print(f"Extracted binary column: {col}")
    
    # Drop temporary columns
    cols_to_drop = ['amenities_cleaned', 'amenities_list', 'amenities']
    df.drop(columns=[col for col in cols_to_drop if col in df.columns], inplace=True)
else:
    print("No amenities column found")

Extracted binary column: Has_Wifi
Extracted binary column: Has_Kitchen
Extracted binary column: Has_Heating
Extracted binary column: Has_TV
Extracted binary column: Has_Essentials
Extracted binary column: Has_Hair_Dryer
Extracted binary column: Has_Iron
Extracted binary column: Has_Free_Parking
Extracted binary column: Has_Hangers
Extracted binary column: Has_Laptop_Friendly_Workspace

In [208]:
import pandas as pd

# One-hot encode room_type
print("Columns before neighbourhood_cleansed block:", df.columns.tolist())  # Debug print to check state
if 'neighbourhood_cleansed' in df.columns:
    print("Current columns before processing:", df.columns.tolist())  # Debug print
    
    # Check for existing neighbourhood_cleansed dummies and drop them
    neighbourhood_dummies = [col for col in df.columns if col.startswith('neighbourhood_')]
    if room_dummies:
        df.drop(columns=room_dummies, inplace=True)
        print(f"Dropped existing neighbourhood_cleansed dummies: {neighbourhood_dummies}")
    
    # Encode and drop original column
    df['neighbourhood_cleansed'] = df['neighbourhood_cleansed'].fillna('Unknown')
    neighbourhood_dummies = pd.get_dummies(df['neighbourhood_cleansed'], prefix='neighbourhood', drop_first=True)
    df = pd.concat([df, neighbourhood_dummies], axis=1)
    df.drop(columns=['neighbourhood_cleansed'], inplace=True)  # Drop original after encoding
    print("One-hot encoded 'neighbourhood_cleansed' into dummies:", neighbourhood_dummies.columns.tolist())
    print("Columns after processing:", df.columns.tolist())  # Debug print
else:
    print("'neighbourhood_cleansed' not found in dataset during this run. Dummies may already be encoded or column was dropped.")

Columns before neighbourhood_cleansed block: ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'latitude', 'longitude', 'property_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'price_log', 'host_age_days', 'days_since_last_review', 'season', 'avg_review_score', 'host_has_profile_pic_binary', 'host_identity_verified_binary', 'accommodates_bedrooms', 'min_nights_reviews', 'Has_Wifi', 'Has_Kitchen', 'Has_Heating', 'Has_TV', 'Has_Essentials', 'Has_Hair_Dryer', 'Has_Iron', 'Has_Free_Parking', 'Has_Hangers', 'Has_Laptop_Friendly_Workspace']
'neighbourhood_cleansed' not found in dataset during this run. Dummies may already be encoded or column was dropped.

# One-hot encode neighbourhood_cleansed as sub-region dummies
if 'neighbourhood_cleansed' in df.columns:
    # Check for existing neighbourhood_cleansed dummies and drop them
    neigh_dummies = [col for col in df.columns if col.startswith('neighbourhood_cleansed_')]
    if neigh_dummies:
        df.drop(columns=neigh_dummies, inplace=True)
        print(f"Dropped existing neighbourhood_cleansed dummies: {neigh_dummies}")
    
    # Encode and drop original column
    df = pd.get_dummies(df, columns=['neighbourhood_cleansed'], drop_first=True)
    df.drop(columns=['neighbourhood_cleansed'], inplace=True)  # Drop original if still present
    print("One-hot encoded 'neighbourhood_cleansed' and dropped original column")
else:
    print("'neighbourhood_cleansed' not found in dataset.")

In [209]:
import math
import numpy as np

# Define haversine_distance function outside the if block for reusability
def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in kilometers
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    distance_km = R * c
    return distance_km

# Add geospatial feature: distance to city center (if latitude/longitude available)
if 'latitude' in df.columns and 'longitude' in df.columns:
    # Check for and handle NaN values (option to drop NaN rows instead of filling with 0)
    df = df.dropna(subset=['latitude', 'longitude'])  # Drop rows with missing lat/long
    # Alternatively, use fillna if dropping is not preferred: df['latitude'] = df['latitude'].fillna(0)
    # df['longitude'] = df['longitude'].fillna(0)

    # Check for existing distance_to_center_km columns and drop duplicates
    distance_cols = [col for col in df.columns if col.startswith('distance_to_center_km')]
    if distance_cols:
        df.drop(columns=distance_cols[1:], inplace=True)  # Keep the first, drop others
        print(f"Dropped duplicate distance columns: {distance_cols[1:]}")

    # Vectorized calculation for better performance
    if 'distance_to_center_km' not in df.columns:
        lat1 = df['latitude'].values
        lon1 = df['longitude'].values
        city_center_lat, city_center_lon = 49.2827, -123.1207  # Vancouver city center (adjust if different)
        lat2 = np.full(len(df), city_center_lat)
        lon2 = np.full(len(df), city_center_lon)
        
        dlat = np.radians(lat2 - lat1)
        dlon = np.radians(lon2 - lon1)
        a = np.sin(dlat/2)**2 + np.cos(np.radians(lat1)) * np.cos(np.radians(lat2)) * np.sin(dlon/2)**2
        c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
        df['distance_to_center_km'] = 6371 * c
    else:
        print("distance_to_center_km already exists, skipping recalculation.")

    # Update numerical_features only if not already present
    if 'distance_to_center_km' not in numerical_features:
        numerical_features.append('distance_to_center_km')
    print("Added or verified 'distance_to_center_km'")
else:
    print("'latitude' or 'longitude' not found in dataset.")

Added or verified 'distance_to_center_km'

In [210]:
# Drop temporary columns
cols_to_drop = ['amenities_cleaned', 'amenities_list', 'amenities', 'last_review', 'host_since', 'latitude', 'longitude']
df.drop(columns=[col for col in cols_to_drop if col in df.columns], inplace=True)

In [211]:
binary_amenities # Debug print to check binary amenities

['host_has_profile_pic_binary',
 'host_identity_verified_binary',
 'Has_Wifi',
 'Has_Kitchen',
 'Has_Heating',
 'Has_TV',
 'Has_Essentials',
 'Has_Hair_Dryer',
 'Has_Iron',
 'Has_Free_Parking',
 'Has_Hangers',
 'Has_Laptop_Friendly_Workspace']

In [212]:
# Remove original categorical columns if they're no longer in df
categorical_features = [col for col in categorical_features if col in df.columns]

# Rebuild selected_features safely
selected_features = (
    numerical_features +
    categorical_features +
    binary_amenities +
    [col for col in df.columns if col.startswith('room_')] +
    [col for col in df.columns if col.startswith('neighbourhood_')]
)

# Check which of the selected features are missing (if any)
missing = [col for col in selected_features + ['price'] if col not in df.columns]
if missing:
    print("Missing columns:", missing)

# Then select only the available ones
df = df[[col for col in selected_features + ['price'] if col in df.columns]]

# Select only engineered features for modeling
selected_features = (numerical_features + categorical_features + binary_amenities + 
                    [col for col in df.columns if col.startswith('room_')] + 
                    [col for col in df.columns if col.startswith('neighbourhood_cleansed_')])
df = df[selected_features + ['price']]  # Include target for modeling

In [213]:
# Save processed dataset
output_path = Path("data/processed/featured_listings.csv")
try:
    df.to_csv(output_path, index=False)
    print(f"Saved feature-engineered dataset to {output_path} with shape: {df.shape}")
except Exception as e:
    print(f"Error saving to {output_path}: {e}")
    raise

Saved feature-engineered dataset to data\processed\featured_listings.csv with shape: (4238, 30)

In [214]:
# Verify data
print("Columns:", df.columns.tolist())

Columns: ['accommodates', 'bathrooms', 'bedrooms', 'beds', 'minimum_nights', 'maximum_nights', 'number_of_reviews', 'review_scores_rating', 'host_age_days', 'days_since_last_review', 'avg_review_score', 'accommodates_bedrooms', 'min_nights_reviews', 'season', 'distance_to_center_km', 'host_is_superhost', 'instant_bookable', 'host_has_profile_pic_binary', 'host_identity_verified_binary', 'Has_Wifi', 'Has_Kitchen', 'Has_Heating', 'Has_TV', 'Has_Essentials', 'Has_Hair_Dryer', 'Has_Iron', 'Has_Free_Parking', 'Has_Hangers', 'Has_Laptop_Friendly_Workspace', 'price']